name: CI

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:

jobs:

  ci:
    name: Validate converting to JSONs
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        uses: taiki-e/install-action@v2
        with:
          tool: yj

      - name: Check converting
        run: ./convert.sh

      - name: Get versions
        id: version
        run: |
          next="v$(cat VERSION)"
          echo "next=$next" >> "$GITHUB_OUTPUT"

    outputs:
      next_version: ${{ steps.version.outputs.next }}

  tag:
    name: Tag
    needs: ci
    uses: transpaer/github-workflows/.github/workflows/tag-version.yml@v0.1.1
    permissions:
      contents: write
    with:
      next_version: ${{ needs.ci.outputs.next_version }}
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
